pipeline {
    agent any
    parameters {
        choice(name: 'act', choices: ['apply', 'destroy'], description: 'Choose Terraform action')
    }
    environment{
        TF_DIR = "Day-2"
    }
    stages {
        stage('git') {
            steps {
                git 'https://github.com/dhanu-sri01/Terraform.git'
            }
        }
        stage('init') {
            steps {
                dir("${env.TF_VAR}"){
                sh 'terraform init'
                }
            }
        }
        stage('plan') {
            steps {
                dir("${env.TF_DIR}"){
                sh 'terraform plan'
                }
            }
        }
        stage('apply') {
            steps {
                dir("${env.TF_DIR}"){
                sh "terraform ${params.act} -auto-approve"
                }
            }
        }
    }
}
